# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    strategy:
      matrix:
        include:
          - python-version: '3.6'
            plone-version: '5.2'
          - python-version: '3.7'
            plone-version: '5.2'
          - python-version: '3.7'
            plone-version: '6.0'
          - python-version: '3.8'
            plone-version: '5.2'
          - python-version: '3.8'
            plone-version: '6.0'
          - python-version: '3.9'
            plone-version: '6.0'

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Cache eggs
      uses: actions/cache@v2
      env:
        cache-name: cache-eggs
      with:
        path: ./eggs
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}-${{ matrix.plone-version }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies and run buildout
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_plone-${{ matrix.plone-version }}.x.txt
        buildout -Nt 5 -c plone-${{ matrix.plone-version }}.x.cfg

    - name: Install Firefox
      uses: browser-actions/setup-firefox@latest
      with:
        firefox-version: '92.0'

    - name: Xvfb
      run: Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

    - name: Test
      env:
        DISPLAY: :99
      run: |
        bin/test --all
